# Generated by Django 5.1.3 on 2024-11-12 01:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomArticlePage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.articlepage')),
                ('sku', models.CharField(default='EFD357E694EA', max_length=12, unique=True, verbose_name='SKU')),
                ('additional_content', wagtail.fields.RichTextField(blank=True, help_text='Rich text content for extra details.', verbose_name='Additional Rich Content')),
            ],
            options={
                'verbose_name': 'Custom Article Page',
            },
            bases=('website.articlepage',),
        ),
    ]
