# Generated by Django 5.1.3 on 2024-11-12 02:47

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_customarticlepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customarticlepage',
            name='sku',
            field=models.CharField(default=website.models.generate_unique_sku, max_length=12, unique=True, verbose_name='SKU'),
        ),
    ]
